In [1]:
# Importar libreria Geopandas
import geopandas as gpd

In [2]:
# Lectura de archivo
gdf = gpd.read_file("Datos/Centros_Salud.shp", engine="pyogrio")

In [3]:
gdf

,id_dera,nombre,direccion,telefono,web,localidad,cod_mun,municipio,provincia,geometry
0,1.121310e+13,Los Pascuales,"TRAVESIA AVENIDA PUERTA (LA), 0",953439008,https://web.sas.junta-andalucia.es/servicioand...,Los Pascuales,23072,La Puerta de Segura,Jaén,MULTIPOINT ((515555.677 4248392.575))
1,1.121310e+13,Benamaurel,"CALLE CALDERON DE LA BARCA, 0",958869608,https://web.sas.junta-andalucia.es/servicioand...,Benamaurel,18029,Benamaurel,Granada,MULTIPOINT ((526681.975 4162248.628))
2,1.121310e+13,El Alcornocal,"CALLE CASTELAR (ALCORNOCAL), 5",600165925,https://web.sas.junta-andalucia.es/servicioand...,El Alcornocal,14029,Fuente Obejuna,Córdoba,MULTIPOINT ((295900.925 4228500.376))
3,1.121310e+13,El Molar,"AVENIDA ANDALUCIA (DE), 12",953105134,https://web.sas.junta-andalucia.es/servicioand...,El Molar,23028,Cazorla,Jaén,MULTIPOINT ((486809.08 4203642.59))
4,1.121310e+13,Almayate Alto,"CALLE FARMACEUTICO MORENO CHICA, 1",951289328,https://web.sas.junta-andalucia.es/servicioand...,Almayate Bajo,29094,Vélez-Málaga,Málaga,MULTIPOINT ((399131.892 4065564.99))
...,...,...,...,...,...,...,...,...,...,...
1511,1.121310e+13,Nechite,"CALLE PLAZA (DE LA), 5",600160078,https://web.sas.junta-andalucia.es/servicioand...,Nechite,18183,Válor,Granada,MULTIPOINT ((493637.813 4095204.083))
1512,1.121310e+13,San Sebastián de los Ballesteros,"CALLE NUEVAS POBLACIONES, 17",957307551,https://web.sas.junta-andalucia.es/servicioand...,San Sebastián de los Ballesteros,14059,San Sebastián de los Ballesteros,Córdoba,MULTIPOINT ((339056.788 4168831.519))
1513,1.121310e+13,Zagrilla,"PLAZA IGLESIA (DE LA) (ZAGRILLA ALTA), 10",957703753,https://web.sas.junta-andalucia.es/servicioand...,Zagrilla Alta,14055,Priego de Córdoba,Córdoba,MULTIPOINT ((390125.307 4149608.512))
1514,1.121310e+13,Terreros,"AVENIDA DEL MEDITERRANEO, 0",950474790,https://web.sas.junta-andalucia.es/servicioand...,San Juan de Terreros,04075,Pulpí,Almería,MULTIPOINT ((618126.951 4135749.67))
1515,1.121310e+13,Baena Dr. Ignacio Osuna Gómez,"CALLE SALVADOR MUÑOZ, 20",957699529,https://web.sas.junta-andalucia.es/servicioand...,Baena,14007,Baena,Córdoba,MULTIPOINT ((383391.944 4164377.662))

In [4]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=['id_dera', 'nombre', 'direccion', 'telefono', 'web', 'localidad', 'cod_mun', 'geometry'])

In [5]:
gdf

                             municipio provincia
0                  La Puerta de Segura      Jaén
1                           Benamaurel   Granada
2                       Fuente Obejuna   Córdoba
3                              Cazorla      Jaén
4                         Vélez-Málaga    Málaga
...                                ...       ...
1511                             Válor   Granada
1512  San Sebastián de los Ballesteros   Córdoba
1513                 Priego de Córdoba   Córdoba
1514                             Pulpí   Almería
1515                             Baena   Córdoba

[1516 rows x 2 columns]

In [6]:
gdf = gpd.read_file("Datos/Hospitales.shp", engine="pyogrio")

In [7]:
gdf

,id_dera,nombre,tipo,sistema_sa,direccion,web,localidad,cod_mun,municipio,provincia,geometry
0,1.121320e+13,HOSPITAL SAN JUAN DE DIOS DE SEVILLA,Hospital,Privado,"AVENIDA EDUARDO DATO, 42",https://web.sas.junta-andalucia.es/servicioand...,Sevilla,41091,Sevilla,Sevilla,MULTIPOINT ((237119.999 4141377.321))
1,1.121320e+13,HOSPITAL VIRGEN DE LA VICTORIA,Hospital,Público,"CALLE DEMOSTENES, 8",https://web.sas.junta-andalucia.es/servicioand...,Málaga,29067,Málaga,Málaga,MULTIPOINT ((368045.226 4064752.167))
2,1.121320e+13,HOSPITAL QUIRONSALUD MARBELLA,Hospital,Privado,"AVENIDA SEVERO OCHOA, 32",https://web.sas.junta-andalucia.es/servicioand...,Marbella,29069,Marbella,Málaga,MULTIPOINT ((332153.091 4042031.302))
3,1.121320e+13,Centro de Diagnóstico y Tratamiento del Hospit...,Centro de consultas externas,Público,"AVENIDA DEL EJERCITO ESPAÑOL, 12",https://web.sas.junta-andalucia.es/servicioand...,Jaén,23050,Jaén,Jaén,MULTIPOINT ((430149.8 4181144.98))
4,1.121320e+13,HOSPITAL DE ALTA RESOLUCION DE UTRERA,Hospital,Público,"AVENIDA BRIGADAS INTERNACIONALES, 0",https://web.sas.junta-andalucia.es/servicioand...,Utrera,41095,Utrera,Sevilla,MULTIPOINT ((252738.481 4118059.733))
...,...,...,...,...,...,...,...,...,...,...,...
178,1.121320e+13,CENTRO ASISTENCIAL HERMANAS HOSPITALARIAS DEL ...,Hospital,Privado,"CALLE SAN JUAN BOSCO, 41",https://web.sas.junta-andalucia.es/servicioand...,Málaga,29067,Málaga,Málaga,MULTIPOINT ((373019.869 4066247.253))
179,1.121320e+13,HOSPITAL SAN CARLOS DE SAN FERNANDO,Hospital,Público,"PASEO CAPITAN CONFORTO, S/N",https://web.sas.junta-andalucia.es/servicioand...,San Fernando,11031,San Fernando,Cádiz,MULTIPOINT ((213777.47 4041935.42))
180,1.121320e+13,HOSPITAL PUERTA DE ANDALUCIA,Hospital,Público,"CARRETERA J-12, 32",https://web.sas.junta-andalucia.es/servicioand...,Jaén,23050,Jaén,Jaén,MULTIPOINT ((431354.389 4183335.096))
181,1.121320e+13,Centro de consultas externas de Marchena,Centro de consultas externas,Público,"AVENIDA MAESTRO SANTOS RUANO, S/N",https://web.sas.junta-andalucia.es/servicioand...,Marchena,41060,Marchena,Sevilla,MULTIPOINT ((285478.33 4134582.987))
182,1.121320e+13,HOSPITAL INFANTA MARGARITA,Hospital,Público,"AVENIDA GONGORA, 9 - Hospital Infanta Margarita",https://web.sas.junta-andalucia.es/servicioand...,Cabra,14013,Cabra,Córdoba,MULTIPOINT ((373958.987 4147776.469))

In [8]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=['id_dera', 'web', 'cod_mun', 'geometry'])

In [9]:
gdf

,nombre,tipo,sistema_sa,direccion,localidad,municipio,provincia
0,HOSPITAL SAN JUAN DE DIOS DE SEVILLA,Hospital,Privado,"AVENIDA EDUARDO DATO, 42",Sevilla,Sevilla,Sevilla
1,HOSPITAL VIRGEN DE LA VICTORIA,Hospital,Público,"CALLE DEMOSTENES, 8",Málaga,Málaga,Málaga
2,HOSPITAL QUIRONSALUD MARBELLA,Hospital,Privado,"AVENIDA SEVERO OCHOA, 32",Marbella,Marbella,Málaga
3,Centro de Diagnóstico y Tratamiento del Hospit...,Centro de consultas externas,Público,"AVENIDA DEL EJERCITO ESPAÑOL, 12",Jaén,Jaén,Jaén
4,HOSPITAL DE ALTA RESOLUCION DE UTRERA,Hospital,Público,"AVENIDA BRIGADAS INTERNACIONALES, 0",Utrera,Utrera,Sevilla
...,...,...,...,...,...,...,...
178,CENTRO ASISTENCIAL HERMANAS HOSPITALARIAS DEL ...,Hospital,Privado,"CALLE SAN JUAN BOSCO, 41",Málaga,Málaga,Málaga
179,HOSPITAL SAN CARLOS DE SAN FERNANDO,Hospital,Público,"PASEO CAPITAN CONFORTO, S/N",San Fernando,San Fernando,Cádiz
180,HOSPITAL PUERTA DE ANDALUCIA,Hospital,Público,"CARRETERA J-12, 32",Jaén,Jaén,Jaén
181,Centro de consultas externas de Marchena,Centro de consultas externas,Público,"AVENIDA MAESTRO SANTOS RUANO, S/N",Marchena,Marchena,Sevilla
182,HOSPITAL INFANTA MARGARITA,Hospital,Público,"AVENIDA GONGORA, 9 - Hospital Infanta Margarita",Cabra,Cabra,Córdoba

In [10]:
gdf = gpd.read_file("Datos/Parques.shp", engine="pyogrio")

In [11]:
gdf

,id_dera,nombre,tipo,geometry
0,1.070550e+13,Sin dato,Parque,"POLYGON ((444906.196 4115298.675, 444995.117 4..."
1,1.070550e+13,Sin dato,Jardín,"POLYGON ((229132.476 4138664.121, 229137.515 4..."
2,1.070550e+13,Sin dato,Parque,"POLYGON ((414395.535 4173214.811, 414494.871 4..."
3,1.070550e+13,Sin dato,Parque,"POLYGON ((445008.359 4115219.725, 445069.088 4..."
4,1.070550e+13,Sin dato,Parque,"POLYGON ((414548.827 4173232.065, 414717.638 4..."
...,...,...,...,...
9274,1.070550e+13,Sin dato,Parque,"POLYGON ((517305.832 4069616.61, 517363.596 40..."
9275,1.070550e+13,Sin dato,Plaza,"POLYGON ((213075.664 4040931.035, 213102.612 4..."
9276,1.070550e+13,Sin dato,Jardín,"POLYGON ((401307.45 4068603.149, 401318.37 406..."
9277,1.070550e+13,Sin dato,Jardín,"POLYGON ((236545.432 4152612.1, 236561.181 415..."
9278,1.070550e+13,Sin dato,Parque Canino,"POLYGON ((240333.571 4135917.435, 240309.828 4..."

In [12]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=['id_dera', 'nombre', 'geometry'])

In [13]:
gdf

               tipo
0            Parque
1            Jardín
2            Parque
3            Parque
4            Parque
...             ...
9274         Parque
9275          Plaza
9276         Jardín
9277         Jardín
9278  Parque Canino

[9279 rows x 1 columns]

In [14]:
gdf = gpd.read_file("Datos/Poblacion.shp", engine="pyogrio")

In [15]:
gdf

,id_dera,cod_sipob,pob_ine,nombre,nivel,cod_mun,municipio,provincia,geometry
0,1.072400e+13,040060004990012,No,Cortijos de Esteban,Diseminado,04006,Albox,Almería,"POLYGON ((580059.063 4151157.388, 580072.82 41..."
1,1.072400e+13,239040025990005,No,Cortijos de Parralejo Bajo,Diseminado,23904,Santiago-Pontones,Jaén,"POLYGON ((542090.47 4229688.85, 542061.48 4229..."
2,1.072400e+13,040270001990004,No,Cortijos de los Pinchos Bajos,Diseminado,04027,Benizalón,Almería,"POLYGON ((568179.99 4116618.87, 568205.39 4116..."
3,1.072400e+13,040820002990036,No,Cortijos de los Zarzales,Diseminado,04082,Senés,Almería,"POLYGON ((559890.294 4115281.836, 559909.378 4..."
4,1.072400e+13,180760001990043,No,Depósito,Diseminado,18076,Fonelas,Granada,"POLYGON ((483867.026 4140670.92, 483877.812 41..."
...,...,...,...,...,...,...,...,...,...
57614,1.072400e+13,040940005990007,No,Cortijos de José Meca,Diseminado,04094,Turrillas,Almería,"POLYGON ((563243.558 4098886.188, 563279.062 4..."
57615,1.072400e+13,180070002990004,No,Depósito,Diseminado,18007,Albuñuelas,Granada,"POLYGON ((444714.916 4087435.883, 444717.907 4..."
57616,1.072400e+13,180200004010008,No,Cortjo del Pajonal,Diseminado,18020,Arenas del Rey,Granada,"POLYGON ((422960.965 4096765.978, 422983.928 4..."
57617,1.072400e+13,110040003990009,No,Cortijos de la Joya,Diseminado,11004,Algeciras,Cádiz,"POLYGON ((274482.51 3993995.8, 274487.457 3994..."
57618,1.072400e+13,239040035990004,No,Cortijos de las Fontanillas,Diseminado,23904,Santiago-Pontones,Jaén,"POLYGON ((541920.758 4221401.133, 541935.462 4..."

In [16]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=['id_dera', 'cod_sipob', 'pob_ine', 'nombre', 'nivel', 'cod_mun', 'geometry'])

In [17]:
gdf

               municipio provincia
0                  Albox   Almería
1      Santiago-Pontones      Jaén
2              Benizalón   Almería
3                  Senés   Almería
4                Fonelas   Granada
...                  ...       ...
57614          Turrillas   Almería
57615         Albuñuelas   Granada
57616     Arenas del Rey   Granada
57617          Algeciras     Cádiz
57618  Santiago-Pontones      Jaén

[57619 rows x 2 columns]

In [18]:
gdf = gpd.read_file("Datos/Zonas_Verdes.shp", engine="pyogrio")

In [19]:
gdf

,id_dera,nombre,tipo,geometry
0,1.070550e+13,Sin dato,Parque,"POLYGON ((444906.196 4115298.675, 444995.117 4..."
1,1.070550e+13,Sin dato,Jardín,"POLYGON ((229132.476 4138664.121, 229137.515 4..."
2,1.070550e+13,Sin dato,Parque,"POLYGON ((414395.535 4173214.811, 414494.871 4..."
3,1.070550e+13,Sin dato,Parque,"POLYGON ((445008.359 4115219.725, 445069.088 4..."
4,1.070550e+13,Sin dato,Parque,"POLYGON ((414548.827 4173232.065, 414717.638 4..."
...,...,...,...,...
9274,1.070550e+13,Sin dato,Parque,"POLYGON ((517305.832 4069616.61, 517363.596 40..."
9275,1.070550e+13,Sin dato,Plaza,"POLYGON ((213075.664 4040931.035, 213102.612 4..."
9276,1.070550e+13,Sin dato,Jardín,"POLYGON ((401307.45 4068603.149, 401318.37 406..."
9277,1.070550e+13,Sin dato,Jardín,"POLYGON ((236545.432 4152612.1, 236561.181 415..."
9278,1.070550e+13,Sin dato,Parque Canino,"POLYGON ((240333.571 4135917.435, 240309.828 4..."

In [20]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=['id_dera', 'nombre', 'geometry'])

In [21]:
gdf

               tipo
0            Parque
1            Jardín
2            Parque
3            Parque
4            Parque
...             ...
9274         Parque
9275          Plaza
9276         Jardín
9277         Jardín
9278  Parque Canino

[9279 rows x 1 columns]